name: PR
on: pull_request
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x

      - name: Install Dependencies and Build
        run: |
          yarn
          yarn build

      - name: Hosting Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PATIENT_TRACKER_D45AE }}'
          projectId: patient-tracker-d45ae
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x
      
      - name: Install and Run Tests
        run: |
          yarn
          yarn test
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x
      
      - name: Install
        run: |
          yarn global add firebase-tools
          yarn

      # TODO: optimize e2e for ci with parallel tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.6.1
        with:
          command: yarn e2e
