name: PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x

      - name: Install Dependencies and Build
        run: |
          yarn
          yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with: 
          name: build artifacts
          path: build/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: build
      
      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x
      
      - name: Install and Run Tests
        run: |
          yarn
          yarn test
        env:
          CI: true

  deploy_preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: build

      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PATIENT_TRACKER_D45AE }}'
          projectId: patient-tracker-d45ae
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
